

- name: python | install app python and system dependencies
  apt: name={{item}} state=present
  with_items:
    - python
    - python-dev
    - python3
    - python3-dev
    - python-software-properties
    - python-pip
    - python3-pip
    - python3-virtualenv
    - python-virtualenv
    - virtualenvwrapper
    - build-essential
    - libavcodec-dev
    - libavdevice-dev
    - libavformat-dev
    - libavresample-dev
    - libavutil-dev
    - libbz2-dev
    - libffi-dev
    - libghc-text-icu-dev
    - libjpeg-dev
    - libncurses5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libswscale-dev
    - libxml2
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
    - llvm
    - node-less
    - git
    - mercurial
    - curl
    - wget
    - redis-server
    - pkg-config


- name: app | get source via git
  git: repo={{PROJECT_URL}} dest=/app/src version={{GIT_VERSION|default('master')}}
  become_user: app

#- name: app | upgrade pip and wheel
#  pip: name={{item.name}} state=latest virtualenv=/app/venv virtualenv_python=python3.4
#  become_user: app

  with_items:
    - { name: 'pip'}
    - { name: 'wheel'}
    - { name: 'setuptools'}

- name: app | install project requirements
  pip:
    requirements: /app/src/requirements.txt
    virtualenv: /app/venv
    chdir: /app/
    virtualenv_python: python3.4
  become_user: app

#- name: app | install src
#  pip: chdir='/app/src/' virtualenv=/app/venv virtualenv_python=python3.4 editable=True name='.'
#  become_user: app
#
#- name: apps | collectstatic
#  command: /app/venv/bin/python /app/src/manage.py collectstatic --noinput
#  become_user: app
#
#- name: apps | db migrate
#  command: /app/venv/bin/python /app/src/manage.py migrate --noinput
#  become_user: app
#
#- name: app | copy project-specific ini file for uWSGI
#  template: src=templates/uwsgi.ini.j2  dest=/etc/uwsgi-emperor/vassals/{{PROJECT_NAME}}.ini
#
#- name: app | chown media directory
#  file:
#    path: /app/media
#    owner: app
#    group: www-data
#    recurse: yes
#
#- name: app | reload uwsgi app
#  file:
#    path: /tmp/app.reload
#    state: touch
