# file: site.yml
# Master playbook

- hosts: all
  become: yes
  become_user: "root"
  pre_tasks:
    - apt: upgrade=dist update_cache=yes
    - apt: name={{item}} state=present
      with_items:
        - libpcre3
        - libcap-dev
        - libpcre3-dev
        - vim
        - tmux

    - shell: date +%s | sha256sum | base64 | head -c 32 > /root/.djkey
      args:
        creates: /root/.djkey
    - shell: date +%s | sha256sum | base64 | head -c 32 >  /root/.dbpass
      args:
        creates: /root/.dbpass
    - fetch: src=/root/.dbpass dest="/tmp" fail_on_missing=yes
    - fetch: src=/root/.djkey dest="/tmp" fail_on_missing=yes

    - include_vars: file=vars/security.yml
    - include_vars: file=vars/postgresql.yml

  vars:
    password: "{{  lookup('file', '/tmp/' + inventory_hostname + '/root/.dbpass') }}"
    key: "{{  lookup('file', '/tmp/' + inventory_hostname + '/root/.djkey')  }}"

  roles:
    - { role: ANXS.postgresql, tags: ['provision']}
    - { role: jdauphant.nginx, nginx_sites: {}, tags: ['provision']}
    - { role: ashwoods.uwsgi-emperor, uwsgi_install_method: pip3, uwsgi_version: '2.0.13.1', uwsgi_uid: 'root', uwsgi_gid: 'root' }
    - { role: djangoapp }

